<script>
	import AOS from 'aos';
	import 'aos/dist/aos.css';

	// Initialize AOS after the component has been mounted
	import { onMount } from 'svelte';

	onMount(() => {
		AOS.init();
	});
</script>

<section class="py-10 sm:py-16 lg:py-24">
	<div class="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8">
		<div class="grid items-center grid-cols-1 gap-12 lg:grid-cols-2">
			<!-- First section -->
			<div>
				<h1
					class="text-6xl font-bold text-transparent lg:text-7xl bg-gradient-to-b from-blueshade20 to-yellowshade20 bg-clip-text"
					data-aos="fade-right"
				>
					Explainer: Advancing a low carbon growth strategy
				</h1>
				<p class="mt-8 text-2xl text-gray-700 lg:text-xl" data-aos="fade-right">
					High income, inclusion and sustainability are the guideposts for Indonesia to realise its
					Vision 2045 and become a “sovereign, advanced, fair and prosperous nation” – the adoption
					of a low carbon growth strategy is crucial to staying on course.
				</p>
				<div class="mt-10 sm:flex sm:items-center sm:space-x-8" data-aos="fade-right">
					<a
						href="/"
						title=""
						class="inline-flex items-center justify-center px-10 py-4 text-xl font-semibold text-white rounded-full bg-blueshade20 hover:bg-yellowshade20 hover:underline lg:text-lg"
						role="button"
					>
						Start exploring
					</a>
				</div>
			</div>

			<!-- Second section -->
			<div>
				<img
					class="object-cover w-full shadow-xl rounded-xl"
					src="/Indonesia-advance-green-energy.png"
					alt="Generated by: DALL-E"
					data-aos="fade-left"
					data-aos-delay="300"
				/>
				<p class="mt-1 text-sm text-right text-gray-600" data-aos="fade-left" data-aos-delay="300">
					Image generated by DALL-E
				</p>
			</div>
		</div>
	</div>
</section>
