<section class="py-10 sm:py-16 lg:py-24 bg-gray-50">
	<div class="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8">
		<div class="grid items-center grid-cols-1 gap-12 lg:grid-cols-2">
			<!-- First section -->
			<div data-aos="fade-right" data-aos-delay="500">
				<h1 class="text-5xl font-bold text-blueshade20">Inclusion</h1>
				<p class="text-2xl font-semibold text-gray-900">Nobody left behind</p>
				<p class="mt-4 mb-2 text-xl text-gray-700">
					Reducing carbon emissions will, in turn, reduce potential the frequency and severity of
					environmental hazards associated with climate change, which often pose greater risks to
					low-income communities.
				</p>
			</div>

			<!-- Second section -->
			<div class="flex flex-col items-center" data-aos="fade-left" data-aos-delay="300">
				<img
					class="object-cover max-w-lg shadow-xl rounded-xl"
					src="/inclusion.png"
					alt="Generated by: DALL-E"
				/>
				<p class="mt-1 text-sm text-gray-600">Image generated by DALL-E</p>
			</div>
		</div>
	</div>
</section>
