<script>
	import AOS from 'aos';
	import 'aos/dist/aos.css';

	// Initialize AOS after the component has been mounted
	import { onMount } from 'svelte';

	onMount(() => {
		AOS.init();
	});
</script>

<section class="py-10 sm:py-16 lg:py-24">
	<div class="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8">
		<div class="grid items-center grid-cols-1 gap-12 lg:grid-cols-2">
			<!-- Second section -->
			<div class="flex flex-col items-center" data-aos="fade-right" data-aos-delay="300">
				<img
					class="object-cover max-w-lg shadow-xl rounded-xl"
					src="/sustainable.png"
					alt="Generated by: DALL-E"
				/>
				<p class="mt-1 text-sm text-gray-600">Image generated by DALL-E</p>
			</div>

			<!-- First section -->
			<div data-aos="fade-left" data-aos-delay="500">
				<h1 class="text-5xl font-bold text-blueshade20">Sustainability</h1>
				<p class="text-2xl font-semibold text-gray-900">Legacy for future generations</p>
				<p class="mt-4 mb-2 text-xl text-gray-700">
					The long-term benefits from natural capital preservation will support economic growth for
					future generations.
				</p>
			</div>
		</div>
	</div>
</section>
